---

- hosts: localhost

  vars:
    headnode_ip: 10.0.0.4
    headnode_hostname: sgci21-containers
    headnode_public_hostname: sgci21-contut.jetstream-cloud.org
#TODO: Add vars certbot role from geerlingguy
# add certbot role
# add httpd.conf file for jhub virtualhost

  tasks:

  - name: create jupyterhub user and group
    user:
      name: jupyterhub
      state: present

  - name: create jupyterhub config dir
    file:
      path: /etc/jupyterhub
      owner: jupyterhub
      group: jupyterhub
      mode: 0755
      state: directory

  - name: install devel deps for building Python
    dnf:
      state: latest
      name:
        - bzip2-devel
        - ncurses-devel
        - gdbm-devel
        - libsqlite3x-devel
        - sqlite-devel
        - libuuid-devel
        - uuid-devel
        - openssl-devel
        - readline-devel
        - zlib-devel
        - libffi-devel
        - xz-devel
        - tk-devel

  - name: install system deps for jhub
    dnf:
      state: latest
      name:
        - nodejs
        - npm
        - httpd
        - httpd-filesystem
        - httpd-tools
        - python3-certbot-apache

  - name: install configurable-http-proxy
    npm:
      name: configurable-http-proxy
      global: yes

  - name: create tmp builddir
    file:
      path: /tmp/build/
      state: directory

  - name: fetch python source
    unarchive:
      src: https://www.python.org/ftp/python/3.8.10/Python-3.8.10.tgz
      dest: /tmp/build/
      remote_src: yes

  - name: run python configure
    command: 
      cmd: ./configure --prefix=/opt/python3
      chdir: /tmp/build/Python-3.8.10

  - name: build python source
    community.general.make:
      target: all
      chdir: /tmp/build/Python-3.8.10
      
  - name: install python
    community.general.make:
      target: install
      chdir: /tmp/build/Python-3.8.10
    become: yes

  - name: run python configure for public build
    command: 
      cmd: ./configure --prefix=/opt/ohpc/pub/compilers/python3
      chdir: /tmp/build/Python-3.8.10

  - name: install python publicly
    community.general.make:
      target: install
      chdir: /tmp/build/Python-3.8.10
    become: yes

  - name: install jupyterhub
    pip: 
      executable: /opt/python3/bin/pip3 
      name: jupyterhub 

  - name: install jupyterlab
    pip:
      executable: /opt/ohpc/pub/compilers/python3/bin/pip3 
      name: jupyterlab

  - name: create jupyterhub service
    template:
      src: jhub_service.j2
      dest: /etc/systemd/system/jupyterhub.service
      mode: 0644
      owner: root
      group: root

#This is hard b/c of Batchspawner config
  - name: install base jupyterhub config
    copy:
      src: jhub_conf.py
      dest: /etc/jupyterhub/jupyterhub_config.py
      owner: jupyterhub
      group: jupyterhub
      mode: 0644

  - name: set headnode ip in jhub_config
    lineinfile:
      regexp: JEC_HEADNODE_IP
      line: "c.JupyterHub.hub_ip = \'{{ headnode_ip }}\' #JEC_HEADNODE_IP"
      path: /etc/jupyterhub/jupyterhub_config.py

  - name: set hostname in jhub_config for batchspawner
    lineinfile:
      regexp: JEC_SPAWNER_HOSTNAME
      line: "c.BatchSpawnerBase.req_host = \'{{ headnode_hostname }}\' #JEC_SPAWNER_HOSTNAME "
      path: /etc/jupyterhub/jupyterhub_config.py

  - name: set hostname in jhub_config for batchspawner
    lineinfile:
      regexp: JEC_PUBLIC_HOSTNAME
      line: "public_hostname = \'{{ headnode_public_hostname }}\' #JEC_PUBLIC_HOSTNAME"
      path: /etc/jupyterhub/jupyterhub_config.py

  - name: install batchspawner to jhub python
    pip:
      name: batchspawner
      executable: /opt/python3/bin/pip3

  - name: start the jupyterhub service
    service:
      name: jupyterhub
      enabled: yes
      state: started
